### ISSUE TITLE
EINVAL error from go runtime in dynamically linked case ?

### ISSUE THREAD

**Issue by lulupac** [vladimirvivien/go-cshared-examples#10]
Thanks for the examples.
I am playing a little bit with cgo at the moment and realized from your C examples that in the dynamically linked case (client1) the `errno` value is already set to EINVAL before even running the client code.
Whereas in the dynamically loaded case (client2), no error is set.

I have just run the two cases, and added `printf("%s", strerror(errno))` at the very beginning of the `main` functions.

Am I missing something or is it that the initialization of the Go runtime may have left an error un-handled in the first case ?

**Comment by vladimirvivien** [comment]
@lulupac thank you for taking the time out to check this example out.  Honestly I am not sure why EINVAL would be set for the `errno`.  Could you paste your code here and I can take a look at it.  Thanks.
