### ISSUE TITLE
Any examples of libraries using this approach?

### ISSUE THREAD

**Issue by confiks** [vladimirvivien/go-cshared-examples#11]
Thanks @vladimirvivien for your article and Github repository. 

I was wondering if you know of any (popular) libraries that use this approach to allow that library to be used from many other languages? 

When asking about this in the Go community, I'm getting a lot of fear and doubt that I shouldn't use `c-shared` libaries for that purpose. For example that the Go would expect to own the process it is running in, and any such attempt would be "fragile". What is your view on that?

**Comment by vladimirvivien** [comment]
@confiks apologies for the late reply. There are many Go-bindings that call into C libraries via cgo.  People have reached to me about about using this approach in their personal projects where external languages call into Go.  

If you want to call Go functions from external lang via c-sharedlib, you should treat the Go lib as a service of sort. Keep the calling client code (from external lang) light and delegate all mem management to Go to avoid having the Go garbage collector stepping on the memory toes of your calling client.  Hope that make sense.

Some of the best practices for pointers discussed here applies - https://golang.org/cmd/cgo/#hdr-Passing_pointers
