### ISSUE TITLE
[Question] C# string array to GO slice

### ISSUE THREAD

**Issue by aleqsss** [vladimirvivien/go-cshared-examples#26]
Hi,

I've successfully used the C# example of:
```
public struct GoSlice
{
    public IntPtr data;
    public long len, cap;
    public GoSlice(IntPtr data, long len, long cap)
    {
        this.data = data;
        this.len = len;
        this.cap = cap;
    }
}

[DllImport(libName)]
public static extern void Sort(GoSlice a);

long[] data = { 77, 12, 5, 99, 28, 23 };
IntPtr data_ptr = Marshal.AllocHGlobal(Buffer.ByteLength(data));
Marshal.Copy(data, 0, data_ptr, data.Length);
var nums = new GoSlice(data_ptr, data.Length, data.Length);
Sort(nums);
Marshal.Copy(nums.data, data, 0, data.Length);
```
To be able to pass in a C# int array to a GO []int.

But how would I go on about passing a C# string array to a GO []string?

Let's say we have the following function in the GO code:
```
//export StringArray
func StringArray(strings []string) {
	for _, element := range strings {
		fmt.Println(element)
	}
}
```
How would I call this, similar as to the []int call above?

Any input is appreciated!

**Comment by aleqsss** [comment]
@Digital-512 excuse me for bothering you, but I could see that you've contributed with the [From C#](https://github.com/vladimirvivien/go-cshared-examples#from-c-1) example. Perhaps you have any input? 🤞

**Comment by Digital-512** [comment]
@aleqsss To pass a C# string array to Go []string, you can define a C# struct that maps to a Go []string and marshal the C# string array to this struct. Here's an example:

C# Struct:
```cs
[StructLayout(LayoutKind.Sequential)]
public struct GoString
{
    public IntPtr data;
    public long len;

    public GoString(string str)
    {
        data = Marshal.StringToHGlobalAnsi(str);
        len = str.Length;
    }

    public static implicit operator GoString(string str) => new GoString(str);
}
```

In the above struct, data holds a pointer to a UTF-8 encoded string and len holds the length of the string.

C# P/Invoke Signature:

```cs
[DllImport(libName, CallingConvention = CallingConvention.Cdecl)]
public static extern void StringArray(GoSlice strings);
```

In the above P/Invoke signature, GoSlice is a struct that we defined earlier and which maps to Go's []string.

Here's an example of how you can call the StringArray function:

```cs
string[] strings = { "hello", "world" };
GoString[] goStrings = new GoString[strings.Length];
for (int i = 0; i < strings.Length; i++)
{
    goStrings[i] = new GoString(strings[i]);
}
IntPtr stringsPtr = Marshal.AllocHGlobal(Marshal.SizeOf<GoString>() * goStrings.Length);
for (int i = 0; i < goStrings.Length; i++)
{
    Marshal.StructureToPtr(goStrings[i], stringsPtr + i * Marshal.SizeOf<GoString>(), false);
}
GoSlice slice = new GoSlice(stringsPtr, goStrings.Length, goStrings.Length);
StringArray(slice);
Marshal.FreeHGlobal(stringsPtr);
```

In the above code, we first convert the C# string array to an array of GoString structs. Then, we allocate unmanaged memory and copy the GoString structs to this memory. We create a GoSlice struct that references this unmanaged memory and pass it to the StringArray function using P/Invoke. Finally, we free the unmanaged memory.

Now, if you have this exported function in Go code:

```go
//export StringArray
func StringArray(strings []string) {
    for _, element := range strings {
        fmt.Println(element)
    }
}
```

The result after executing command `dotnet run` should be like this:

```
> dotnet run
hello
world
```

**Comment by aleqsss** [comment]
@Digital-512

Thanks a bunch for this thorough reply with explanations and examples, trust me when I say that I'm really grateful!

I'll try this out and share my results.

**Comment by vladimirvivien** [comment]
This is wonderful. Thank you both @Digital-512 and @aleqsss .

**Comment by aleqsss** [comment]
I've now tried the example code and adopted it a bit to my scenario, works like a charm. Thanks again!

Will proceed to close this issue (question) now.
