### ISSUE TITLE
-buildmode=c-shared not supported on windows/amd64

### ISSUE THREAD

**Issue by guppy57** [vladimirvivien/go-cshared-examples#6]
Im using go 1.9.3 and just tried to do this with this simple file : 

```
package main

import "C"
import (
	"fmt"
)

//export add
func add(a, b int) int {
	var sum int = a + b
	fmt.Println("DONE")
	return sum
}

func main() {}
```

But kept getting the error above. Is there any way to fix this? Am I using the wrong command?

**Comment by vladimirvivien** [comment]
@guppythegod  Apologies for the delayed response.  You are not doing anything wrong.  However, that flag (`-buildmode=c-shared`) is in deed not supported on Windows platform this point.

**Comment by guppy57** [comment]
Thank you for replying

**Comment by Zireael07** [comment]
Is this still the case? The relevant issue on golang's repo is now closed...

**Comment by vladimirvivien** [comment]
@Zireael07 I haven't checked on this in a while.  Last release OSX support was added.  It's possible windows was added for this upcoming release.

**Comment by SommerEngineering** [comment]
Since Go 1.10, it works also with Windows. Thus, this issue could be closed.

**Comment by vladimirvivien** [comment]
Thank you @SommerEngineering

**Comment by famei** [comment]
![image](https://user-images.githubusercontent.com/61237921/189010932-4a80c01d-75c8-4495-abc7-c42bd33a51f2.png)
![image](https://user-images.githubusercontent.com/61237921/189010953-93099418-5e81-4215-bc4f-976a3b648551.png)
![image](https://user-images.githubusercontent.com/61237921/189011200-3625b45b-6ada-47a9-8d7d-b6fa81806e53.png)
I have the same problem with go 1.19, how should I solve it

**Comment by famei** [comment]
> ![图片](https://user-images.githubusercontent.com/61237921/189010932-4a80c01d-75c8-4495-abc7-c42bd33a51f2.png) ![图片](https://user-images.githubusercontent.com/61237921/189010953-93099418-5e81-4215-bc4f-976a3b648551.png) ![图片](https://user-images.githubusercontent.com/61237921/189011200-3625b45b-6ada-47a9-8d7d-b6fa81806e53.png) 我的 go 1.19 也有同样的问题，我应该怎么解决

![image](https://user-images.githubusercontent.com/61237921/189011340-3c818aa9-a297-47a9-957f-d84dec282689.png)
