### ISSUE TITLE
Can generate the .so file used by the arm Linux platform?

### ISSUE THREAD

**Issue by skyformat99** [vladimirvivien/go-cshared-examples#7]
thanks.
What should I do to transfer the generated so file to the ARM  platform?
target  =>   ARM  embedded linux  OS

**Comment by vladimirvivien** [comment]
You have to compile to target your architecture with something like this `GOOS=linux GOARCH=arm GOARM=6 go build -buildmode=cshared -o plugin.so source_code.go`
